# Generated by Django 5.1.3 on 2025-02-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnePlusTwo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='size',
            field=models.CharField(default='M', max_length=10),
        ),
    ]
