# Generated by Django 5.1.3 on 2025-02-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnePlusTwo', '0002_cartitems_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
